### ISSUE TITLE
Eu como Usuário, Desejo CADASTRAR, EDITAR, LISTAR e DELETAR indicadores para que eu possa utiliza-lo. 

### ISSUE THREAD

**Issue by lucasferreiraunicef** [UNICEF01/MAAP#299]
**Descrição:** 

**Regra de negócio:**

Os indicadores devem ser cadastrados, editados, listados e deletados. Devem estar disponíveis para que possam ser setados(Adicionados) a um **programa ou projeto**.

1) Indicador de programa/projeto pode ser utilizado em mais de um programa/projeto.
2) 0 -> N Relacionamentos
3) Indicadores pertencem exclusivamente a cada categoria, ou seja, um indicador de **projeto** poderá ser utilizado somente em **projeto**.
4) Indicadores pertencem exclusivamente a cada categoria, ou seja, um indicador de **programa** poderá ser utilizado somente em **programa**.
5) Para qualquer indicador que seja editado, o sistema deve gerar uma NOTIFICACÃO para os **profiles Admins** do **projeto ou programa.**

**Exceto:**

Tabs - DESTE/DE TODOS
Tela de listagem de TODOS OS INDICADORES

**Links Úteis:**
[Jornada Indicadores](https://xd.adobe.com/view/5bc066b3-ae2b-40b6-a5da-c55e8cdc4100-0e93/)

**Comment by lucasferreiraunicef** [comment]
Critérios de aceite:

- [ ] Usuário poderá filtrar(Search) o indicador.

- [ ] Deve seguir o fluxo correto da jornada do usuário

- [ ] Deve Conter todos os componentes de tela desenvolvidos com base no protótipo.
