### ISSUE TITLE
[BACK] Criação da tabela nova: Meta Anual; implementar no IndicadorService

### ISSUE THREAD

**Issue by cxelegance-unicef** [UNICEF01/MAAP#348]
- [ ] criar meta_anual
  - [ ] ano (int)
  - [ ] descricao (varchar)
- [ ] criar indicador_meta_anual
  - [ ] indicador_id
  - [ ] meta_id
- [ ] criar Model, Factory, Repository, RepositoryInterface
  - [ ] Repository has getByIndicador() : Collection
- [ ] criar Service
  - [ ] intraRequest: getByIndicador() : Collection
  - [ ] Service consumes relational table's repository
- [ ] MaapTestSeeder needs new entries and must pass
- [ ] Retirar meta anual de todu "Indicador" (Service, Repository, Factory, Model, MaapTestSeeder)
- [ ] implentar nova tabela no IndicadorService
- [ ] update o format do JSON no CRUD do IndicadorService
- [ ] Indicador tests must pass
