### ISSUE TITLE
[Work Plan + Timeline] Iniciativas

### ISSUE THREAD

**Issue by lucasferreiraunicef** [UNICEF01/MAAP#353]
**Descrição:** Uma iniciativa é criada a partir do relacionamento com um **(apenas um) produto** da matriz lógica. Elas são categorizadas ("001 Global..."), possuem instituições relacionadas (dentro do universo de instituições relacionadas ao Programa/Projeto, no momento da sua criação), possuem o campo de palavras-chaves (onde é possível adicionar novas palavras-chaves) e trazem o campo de orçamento alocado (trazendo o valor relacional com o total da contribuição financeira do seu produto da matriz lógica que está relacionado).

![image.png](https://images.zenhubusercontent.com/6232777dbf0d5a6437a41ee5/34b30418-2d1b-40f8-8eec-55210de8ea3e)
**Link:** https://xd.adobe.com/view/7561e78f-c84e-4849-862e-8bdec4ca7a7b-2032/screen/5f888296-8bd7-49c5-a455-1f6882294e8c/specs/ (Telas de 3 a 5)

**Atenção:** 
- as iniciativas cadastradas (de todos os tipos) devem ser exibidas dentro de seus produtos na visualização da matriz lógica.
- O campo de "orçamento alocado" não faz parte deste épico.
- O campo "comentários", presente na [tela 5](https://xd.adobe.com/view/90d79cf9-f5f8-44e0-b5e9-b4b402f174f0-c584/screen/7ff2c7aa-3e43-40ba-b36e-12556bc130dc/) do protótipo não faz parte deste épico

**Comment by lucasferreiraunicef** [comment]
Critérios de aceite:

 

- [ ] Conter a jornada de usuário completa.

 

- [ ] Todas as validações de campo devem estar funcionando.

 

- [ ] Todas as associações de formulário devem estar funcionando.

 

- [ ] Deve Conter todos os componentes de tela desenvolvidos com base no protótipo da sprint atual.

 

- [ ] Deve ser aceito e aprovado em homologação.
