### ISSUE TITLE
[ROLE] Programa e Matriz Lógica de Programa

### ISSUE THREAD

**Issue by lucasferreiraunicef** [UNICEF01/MAAP#376]
**Description:** Para melhor trazer segurança para os usuários da plataforma, devemos desenvolver a camada de **ROLES** que está diretamente ligada a **PERMITIONS**. Para tal, definimos abaixo as respectivas roles e logo abaixo de cada uma, as permissões (As permissões deverão ser tratadas em outro épico, segue link abaixo).

**Epico Permitions para Programas e Matriz logica de programas**: [Link](https://app.zenhub.com/workspaces/maap-611ea94df0ba85000f5283bf/issues/gh/unicef01/maap/373)

[PPT](https://docs.google.com/presentation/d/1U12Uv5OvT2ijag7af9YFPCKlzOBoW8KsvpMUR4M7PDI/edit?usp=sharing)

**Em quais Features devemos aplicar as Roles e Permitions para este épico?**

**Programas:**
- Adicionar Programas
- Editar Programas
- Excluir Programas
- Aprovacão

**Matriz Lógica de Programas:**
- Adicionar Matriz lógica
- Editar Matriz lógica
- Excluir Matriz lógica
- Aprovacão

**Regra de negócio:**

Adm de Programa
    - Criar, Editar, Excluir, Visualizar - Programa & Matriz Lógica
    
    
Editor de Programa
    - Criar, Editar, Excluir e Visualizar - Programa & Matriz Lógica
    
    
Visualizador de Programa
    - Visualizar Programa & Matriz Lógica
    

Link Programa XD: https://xd.adobe.com/view/7fe4c579-972a-4411-8608-1893a168b8dc-2ab7/
Link Matriz Lógica Programa XD: https://xd.adobe.com/view/6ea356df-f452-4ff7-b64a-13446059146c-3bf0/

Link Programa: https://maap.org.br/programs + https://maap.org.br/program/1
Link Matriz Lógica Programa: https://maap.org.br/program/1/matriz/1 + https://maap.org.br/program/1/matriz/1/objetivo-especifico/ + https://maap.org.br/program/1/matriz/1/resultado/

**Comment by lucasferreiraunicef** [comment]
Critérios de aceite:

 

- [x] Conter a jornada de usuário completa.

 

- [x] Todas as validações de campo devem estar funcionando.

 

- [x] Todas as associações de formulário devem estar funcionando.

 

- [x] Deve Conter todos os componentes de tela desenvolvidos com base no protótipo da sprint atual.

 

- [x] Deve ser aceito e aprovado em homologação.
