### ISSUE TITLE
[Aprovacoes] 

### ISSUE THREAD

**Issue by lucasferreiraunicef** [UNICEF01/MAAP#398]
**Description**: A respectiva feature possui o objetivo de permitir que qualquer usuário que pertença à aquele **PROJETO** ou **PROGRAMA** ao realizar uma **criação** ou **edição** seja submetido a uma **APROVACÃO**. 

A regra de aprovacão deverá ser aplicada seguindo as seguintes regras abaixo - **MATRIZ LÓGICA PROGRAMA/PROJETO**:

1) Criação / edição de programas e projetos;

2) Criação / edição de matriz lógica de programas e projetos;

3) Criação / edição de plano de trabalho de programas e projetos;

4) Criação / edição de indicadores de programas e projetos;

5) O botão "APROVAR" fica disponível após um editor ou administrador clicar no botão "ENVIAR PARA APROVAÇÃO";

6) Enquanto faltar algum administrador aprovar, o status do projeto/programa, da matriz, do plano de trabalho e dos indicadores ficam como "aguardando aprovação";

7) Após a aprovação de todos os administradores do programa ou projeto, o status fica como "aprovado"

8) Todos os administradores do programa ou projeto devem aprovar novamente qualquer alteração realizada após já aprovado;

9) A aprovação se dá em lote, ou seja, o administrador visualiza um registro de logs de tudo que foi criado/alterado e aprova tudo de uma vez

10) Será armazenado no banco de dados cada versão aprovada;

11) Para que o administrador consulte a versão anterior é necessário solicitar um backup da versão anterior no banco de dados ou ter gerado um relatório da última versão

Protótipo:

[Link](https://xd.adobe.com/view/52c2f8cb-7688-4a25-aae6-c28d83f03dfd-0791/?hints=off)

**Comment by lucasferreiraunicef** [comment]
Critérios de aceite:

 

- [x] Conter a jornada de usuário completa.

 

- [ ] Todas as validações de campo devem estar funcionando.

 

- [x] Deve Conter todos os componentes de tela desenvolvidos com base no protótipo da sprint atual.

 

- [ ] Deve ser aceito e aprovado em homologação.
