### ISSUE TITLE
Matriz Logica de Projeto

### ISSUE THREAD

**Issue by lucasferreiraunicef** [UNICEF01/MAAP#540]
**Projetos:**

Desenvolver o CRUD de Matriz Logica para Projetos e seus devidos componentes e adaptações:

**Adaptar resultado e produto da matriz logica para projeto -> Tela 2 e 3**

Cabeçalho: Impacto (título de Objetivo Específico, Resultado e/ou Produto); Indicadores (títulos dos indicadores; Metas; Previsão de início; Previsão de fim; Contrapartida não financeira; Contrapartida financeira; **Ações (editar / remover(Disable em Cascata) - por linha)**

**Regra de Contribuição não financeira e financeira ->** 
Resultado é igual a soma dos valores de seus produtos
O Total de Contrapartida financeira e não financeira é a soma dos valores de seus resultados

[Link](https://xd.adobe.com/view/9d5736a5-4d78-4f62-a8fc-6d2625233a3d-c804/) - TELA 1 a 3

**Comment by lucasferreiraunicef** [comment]
Critérios de aceite:

 

- [ ] Conter a jornada de usuário completa.

 

- [ ] Todas as validações de campo devem estar funcionando.

 

- [ ] Todas as associações de formulário devem estar funcionando.

 

- [ ] Deve Conter todos os componentes de tela desenvolvidos com base no protótipo da sprint atual.

 

- [ ] Deve ser aceito e aprovado em homologação.

**Comment by lucasferreiraunicef** [comment]
@ricardosreichert a partir do dia 15/05 + @gucostaunicef planejando as tasks de "MATRIZ LOGICA DE PROJETO".
