### ISSUE TITLE
Plano de Trabalho de Projeto

### ISSUE THREAD

**Issue by ricardosreichert** [UNICEF01/MAAP#545]
![image.png](https://images.zenhubusercontent.com/6238de3ad16134773fdd2395/761e2637-3b8c-47ab-b5d5-6a4777653d02)

**Comment by lucasferreiraunicef** [comment]
Critérios de aceite:

 

- [x] Conter a jornada de usuário completa.

 

- [x] Todas as validações de campo devem estar funcionando.

 

- [x] Todas as associações de formulário devem estar funcionando.

 

- [x] Deve Conter todos os componentes de tela desenvolvidos com base no protótipo da sprint atual.

 

- [x] Deve ser aceito e aprovado em homologação.
