### ISSUE TITLE
ORCAMENTOS em MONITORAMENTO

### ISSUE THREAD

**Issue by lucasferreiraunicef** [UNICEF01/MAAP#639]
Description: Recuperar os dados da API para os componentes abaixo

**FORMULÁRIO DE MONITORAMENTO**

**Total Contribuições
Não-Financeiras**

É o mesmo que CONTRA-PARTIDA NÃO FINANCEIRA TOTAL
<img width="222" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeXV1QWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--813eebf3250a6965102e7413fb8b391cfe382f61/Captura%20de%20Tela%202024-01-09%20a%CC%80s%2011.15.40.png" alt="Captura de Tela 2024-01-09 às 11.15.40.png" />

**TELA: MATRIZ LOGICA**
_________________________________________________________________________

**Total Contribuições
Financeiras planejadas**

É O MESMO QUE CONTRAPARTIDA FINANCEIRA TOTAL
<img width="249" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeSt1QWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--0f0dbce16800776c2219c73b07d5e8ac4a1a8589/Captura%20de%20Tela%202024-01-09%20a%CC%80s%2011.16.25.png" alt="Captura de Tela 2024-01-09 às 11.16.25.png" />

**TELA: MATRIZ LOGICA**

_________________________________________________________________________

**Orçamento
Alocado total**

Programa: é a SOMA de todos os ORCAMENTOS ALOCADOS das iniciativas(COMUM) do programa + a SOMA das contribuições financeiras das instituições UNICEF e ABC dos projetos ou visita de estudo relacionados a este programa.

Projeto: SOMA dos orçamentos alocados das ATIVIDADES do PROJETO.

<img width="208" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeWU3QWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--d7d3f0d6dc1d0bd53a90b1d7161eb1628aa240c6/Captura%20de%20Tela%202024-01-11%20a%CC%80s%2011.04.58.png" alt="Captura de Tela 2024-01-11 às 11.04.58.png" />

**TELA: PLANO DE TRABALHO**

__________________________________________________________________________

**Orçamento
Executado total**

Programa: é a SOMA de todos os ORCAMENTOS EXECUTADOS das ATIVIDADES(INICIATIVAS) do programa + a SOMA de todos os ORCAMENTOS EXECUTADOS das TAREFAS dos projetos/visitas de estudo relacionadas ao programa..

Projeto: é a SOMA de todos os ORCAMENTOS EXECUTADOS das TAREFAS do projeto.

<img width="203" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeW03QWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--10123bfee019a88d6cdfa12352ff789bce3b653c/Captura%20de%20Tela%202024-01-11%20a%CC%80s%2011.05.27.png" alt="Captura de Tela 2024-01-11 às 11.05.27.png" />

**TELA: PLANO DE TRABALHO**

__________________________________________________________________________
**Saldo total para
Execução**

É o valor do ORCAMENTO ALOCADO TOTAL - ORCAMENTO EXECUTADO TOTAL

Tela:
<img width="1312" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNE9iQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--00f1b412e9e6c83bd5ebbca0a2f9277495b5516e/Captura%20de%20Tela%202024-01-04%20a%CC%80s%2011.59.31.png" alt="Captura de Tela 2024-01-04 às 11.59.31.png" />

**Comment by mfreireunicef** [comment]
@lucasferreiraunicef por favor, inserir o XD

**Comment by mfreireunicef** [comment]
@lucasferreiraunicef No consumo da matriz logica em monitoramento existe esses campos:
"total_objetivo_especifico": 0,
"total_resultado": 0,
"total_produto": 0

o que é o que na tela? os demais itens (ja que são 5) viria de onde a informação?

Endpoint: https://api.maap.org.br/api/matriz-logica/13

<img width="474" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBN3lwQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--782013fd9dea9e1f0a4561516f5d5f7ace5be438/Captura%20de%20Tela%202024-01-08%20a%CC%80s%2016.32.28.png" alt="Captura de Tela 2024-01-08 às 16.32.28.png" />

**Comment by lucasferreiraunicef** [comment]
@mfreireunicef itens atualizados com excecão das contrapartidas. Entrei em contato com o Lazaroni para entender se as contrapartidas se equivalem as contribuicões.

**Comment by lucasferreiraunicef** [comment]
Critérios de aceite:

 

- [x] Conter a jornada de usuário completa.

 

- [x] Todas as validações de campo devem estar funcionando.

 

- [x] Todas as associações de formulário devem estar funcionando.

 

- [x] Deve Conter todos os componentes de tela desenvolvidos com base no protótipo da sprint atual.

 

- [x] Deve ser aceito e aprovado em homologação.
